default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 30 } %>

development:
  <<: *default
  database: fonix_chat_development

test:
  <<: *default
  database: fonix_chattest

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
    database: fonix_production
    username: <%= ENV["PGUSER"] || 'fonix' %>
    password: <%= ENV["PGPASSWORD"] || ENV["FONIX_DATABASE_PASSWORD"] %>
    host: <%= ENV["PGHOST"] %>
    port: <%= ENV["PGPORT"] || 5432 %>
  queue:
    <<: *primary_production
  cable:
    <<: *primary_production
  cache:
    <<: *primary_production
